name: Trigger Webhook

on:
  push:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook payload
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"ref": "refs/heads/main"}' \
          $WEBHOOK_URL
